# Generated by Django 4.1 on 2022-08-10 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(blank=True, max_length=50, null=True)),
                ('operator_order', models.IntegerField(blank=True, null=True)),
                ('operator_image_link', models.CharField(blank=True, max_length=50, null=True)),
                ('operator_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Network Operator Info',
                'verbose_name_plural': 'Mobile Network Operators',
            },
        ),
        migrations.CreateModel(
            name='PackageOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_order', models.IntegerField(blank=True, null=True)),
                ('airtime_value', models.FloatField(blank=True, null=True)),
                ('selling_price_ETB', models.FloatField(blank=True, null=True)),
                ('selling_price_USD', models.FloatField(blank=True, null=True)),
                ('discount_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Package Offer Detail',
                'verbose_name_plural': 'Package Offers',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_order', models.IntegerField(blank=True, null=True)),
                ('provider_image_link', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_active', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoter', models.CharField(blank=True, max_length=150, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('promo_discount_rate', models.FloatField(blank=True, null=True)),
                ('promo_expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promotion Discount Detail',
                'verbose_name_plural': 'Promotion Discount Listings',
            },
        ),
        migrations.CreateModel(
            name='Invoces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoices_commit', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoive_uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_phone', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='remit_api.operators')),
                ('package_offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remit_api.packageoffers')),
                ('promo_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='remit_api.promocodes')),
            ],
            options={
                'verbose_name': 'Invoices Detail',
                'verbose_name_plural': 'Invoce Records',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='remit_api.invoces')),
                ('transaction_status', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_amount', models.FloatField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remit_api.paymentmethod')),
            ],
            options={
                'verbose_name': 'Transactions Detail',
                'verbose_name_plural': 'Transactions Records',
            },
        ),
    ]
